### PR TITLE
Hieradata per instances group

### PR DESCRIPTION
**Pull request by etiennedub**
Depends: https://github.com/ComputeCanada/magic_castle/pull/291

### CODE REVIEW

**Comment by cmd-ntrf** [comment]
I had no idea we could define our own lookup function like this. Very interesting.

I worked on a similar issue of having to go from one hieradata YAML file to one per node. Since I did not know about the data_hash option, I created a Ruby script that splits the single YAML file into many.
https://github.com/ComputeCanada/puppet-magic_castle/pull/300/files#diff-6adbf30b836537945a80096517501629e6367673071c450f2293e265155cab63

What do you think is the best approach? Do you think the data_hash option could be used in my case?

**Comment by etiennedub** [comment]
It took me a while to make the `data_hash` work. It's documented a bit [here](https://www.puppet.com/docs/puppet/7/hiera_custom_backends#data_hash_backends), but I mostly used the [original YAML parser](https://github.com/puppetlabs/puppet/blob/main/lib/puppet/functions/yaml_data.rb) function as an example.

I think the `data_hash` approach is more straightforward than calling the script separately. It's also easier to edit the hieradata from Terraform because you don't need to call the script every time.

In your case, you could use the same `data_hash` function (`prefix_lookup`):
```
  - name: "Nodes"
    path: "nodes.yaml"
    options:
      node_prefix: "%{facts.networking.hostname}"
    data_hash: prefix_lookup
```

But if we use this function in multiple places, we should probably rename it to something more generic than "prefix".

**Comment by mboisson** [comment]
Instead of 
```
  - name: "User data"
    glob: "hieradata/*.yaml"
  - name: "Prefix data"
    path: "hieradata/prefix/%{facts.prefix}.yaml"
  - name: "Hostname data"
    path: "hieradata/hostname/%{facts.networking.hostname}.yaml"
``` 
Would it be too late to suggest: 
```
  - name: "User data"
    glob: "hieradata/*.yaml"
  - name: "Prefix data"
    glob: "hieradata/prefix/%{facts.prefix}/*.yaml"
  - name: "Hostname data"
    glob: "hieradata/hostname/%{facts.networking.hostname}/*.yaml"
``` 

 ?

**Comment by cmd-ntrf** [comment]
I think it's a good suggestion, but we should be able to do both: a folder **or** a single file named after the prefix or the hostname.

**Comment by cmd-ntrf** [comment]
Another comment, since hiera.yaml defines a hierarchy, hostname should precedes prefix as it is more specific.

**Comment by etiennedub** [comment]
@cmd-ntrf @mboisson In the end it supports both methods, a folder containing multiples yaml files or a yaml file directly.

```
  - name: "User data"
    glob: "hieradata/*.yaml"
  - name: "Prefix data"
    globs: ["hieradata/prefix/%{facts.prefix}/*.yaml", "hieradata/prefix/%{facts.prefix}.yaml"]
  - name: "Hostname data"
    globs: ["hieradata/hostname/%{facts.networking.hostname}/*.yaml", "hieradata/hostname/%{facts.networking.hostname}.yaml"]
  ```

**Comment by mboisson** [comment]
> Another comment, since hiera.yaml defines a hierarchy, hostname should precedes prefix as it is more specific.

"User data" should also be below "Prefix data", so reverse the order of the 3 ? i.e. 

* Hostname data
* Prefix data
* User data
in that order

**Comment by cmd-ntrf** [comment]
> > Another comment, since hiera.yaml defines a hierarchy, hostname should precedes prefix as it is more specific.
> 
> "User data" should also be below "Prefix data", so reverse the order of the 3 ? i.e.
> 
> * Hostname data
> * Prefix data
> * User data
>   in that order

agreed

**Comment by mboisson** [comment]
Decryption of encrypted secrets is no longer working, the encrypted secrets are now put in the configuration files with their encrypted value, rather than their decrypted one.

**Comment by cmd-ntrf** [comment]
> Decryption of encrypted secrets is no longer working, the encrypted secrets are now put in the configuration files with their encrypted value, rather than their decrypted one.

The following lines need to be added to "Hostname data", "Prefix Data" and "User data" dictonaries:
```
    lookup_key: eyaml_lookup_key # eyaml backend
    options:
      pkcs7_private_key: /etc/puppetlabs/puppet/eyaml/private_key.pkcs7.pem
      pkcs7_public_key:  /etc/puppetlabs/puppet/eyaml/public_key.pkcs7.pem

```

**Comment by mboisson** [comment]
> > Decryption of encrypted secrets is no longer working, the encrypted secrets are now put in the configuration files with their encrypted value, rather than their decrypted one.
> 
> The following lines need to be added to "Hostname data", "Prefix Data" and "User data" dictonaries:
> 
> ```yaml
>     lookup_key: eyaml_lookup_key # eyaml backend
>     options:
>       pkcs7_private_key: /etc/puppetlabs/puppet/eyaml/private_key.pkcs7.pem
>       pkcs7_public_key:  /etc/puppetlabs/puppet/eyaml/public_key.pkcs7.pem
> ```

Indeed, that fixes it.

**Pull request merged**
