### PR TITLE
Use puppet-forge's rsyslog

### PR DESCRIPTION
**Pull request by mboisson**
To avoid this PR from causing issue, one must define these yaml parameters:

```
rsyslog::purge_config_files: false
rsyslog::override_default_config: false
``` 

I am not sure where best to set those

### CODE REVIEW

**Comment by cmd-ntrf** [comment]
One option would be to include the `rsyslog` class in `profile::rsyslog::base` instead of including via `site.yaml`:

```puppet
class profile::rsyslog::base {
  class { 'rsyslog':
    purge_config_files      => false,
    override_default_config => false,
  }
}
```

**Comment by mboisson** [comment]
Ok, done.

**Comment by cmd-ntrf** [comment]
The way we load the imtcp module in profile::rsyslog::server is apparently legacy.

Now that we install the puppet rsyslog module, we could use it the load the imtcp module and configure the port.
https://github.com/voxpupuli/puppet-rsyslog/tree/da7866adef54a658513e5170e445169f3cd13e5d?tab=readme-ov-file#rsyslogconfigmodules

Something like:
```puppet
class { 'rsyslog::config':
  modules => { 
    'imtcp' => {},
  },
  'inputs' => {
    'imtcp' => {
      'type'   => 'imtcp',
      'config' => {
        'port' => '514'
      }
    }
}
```

**Comment by mboisson** [comment]
The reason I have not done it is I wonder what happens with the yaml vs these variables, and where it puts the file. I have not found how to manage multiple rsyslog files with the module, it puts everything in the `rsyslog::target_file` , i.e. in my case: 
```
rsyslog::target_file: 50_alliance_opensearch.conf
``` 

I am not sure it is desirable to merge the MC-specific config with the "external" config ?

**Comment by mboisson** [comment]
ah, the above does not work, in fact... 
```
Feb 08 17:54:33 mgmt1.int.archimedes.c3.ca puppet-agent[3716025]: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Rsyslog] is already declared; cannot redeclare (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/rsyslog.pp, line: 2) (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/rsyslog.pp, line: 2, column: 3) on node mgmt1
``` 

The class already exists

**Comment by mboisson** [comment]
> ah, the above does not work, in fact...
> 
> ```
> Feb 08 17:54:33 mgmt1.int.archimedes.c3.ca puppet-agent[3716025]: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Rsyslog] is already declared; cannot redeclare (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/rsyslog.pp, line: 2) (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/rsyslog.pp, line: 2, column: 3) on node mgmt1
> ```
> 
> The class already exists

ah, nevermind, I just need to remove the `rsyslog` from the explicit list in the tags in my yaml file.

**Comment by mboisson** [comment]
Hum, I got duplicate classes error when including the above on all nodes except the puppet1 node 🤔

**Comment by mboisson** [comment]
Trying to add 
```
class { 'rsyslog::config':
  modules => { 
    'imtcp' => {},
  },
  'inputs' => {
    'imtcp' => {
      'type'   => 'imtcp',
      'config' => {
        'port' => '514'
      }
    }
  }
}
``` 
to the `profile::rsyslog::server` class leads to 
```
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Rsyslog::Config] is already declared; cannot redeclare (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/rsyslog.pp, line: 55) (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/rsyslog.pp, line: 55, column: 3) on node mgmt1
``` 
since I have `include rsyslog::config` in the `profile::rsyslog::client` class and that class is everywhere. How to include `rsyslog::config` while defining parameters for it the class ?

**Comment by cmd-ntrf** [comment]
To avoid duplicate declaration, you could move `include rsyslog::config` from `profile::rsyslog::base` to `profile::rsyslog::client`.

For `profile::rsyslog::server`, you will need to lookup the values for the rsyslog::config that come the hieradata and merge them with the values that were set in the class definition. This is only for values that were set explicitly in the class definition, other values defined in hieradata will find their way to rsyslog::config just fine.
```puppet
class { 'rsyslog::config':
  modules => merge(
    { 'imtcp' => {}, }, 
    lookup('rsyslog::config::modules', undef, undef, {})
  ),
  'inputs' => merge({
    'imtcp' => {
      'type'   => 'imtcp',
      'config' => {
        'port' => '514'
      }
    }
  }, lookup('rsyslog::config::inputs', undef, undef, {}))
}

```

**Comment by mboisson** [comment]
> To avoid duplicate declaration, you could move `include rsyslog::config` from `profile::rsyslog::base` to `profile::rsyslog::client`.

That's already where I put it in https://github.com/ComputeCanada/puppet-magic_castle/pull/321/commits/3c4e6c2e0512ad2a576dec07a748433dd2c3f134 

But the syslog server is *also* a client. That means a single tag can't have both `profile::rsyslog::client` and `profile::rsyslog:server` which is possible at the moment (and is the case in my case, since I want the client config to apply to all nodes)

**Comment by cmd-ntrf** [comment]
Or we circle back to not use puppet rsyslog to configure the server, which right now looks simpler.

**Comment by mboisson** [comment]
Ah, indeed, otherwise we have to also include the logic from the client class inside of the server one...

**Pull request merged**
