### PR TITLE
Fix account zero-padding for nb_accounts < 10

### PR DESCRIPTION
**Pull request by cmd-ntrf**

### CODE REVIEW

**Comment by ocaisa** [comment]
For me, this raises an issue if I want to extend the number of users on the system:
```
Changes to Outputs:
  ~ guest_usernames = "user[1-5]" -> "user[01-10]"
```
so it looks like the previously existing users will get trashed.

**Comment by cmd-ntrf** [comment]
The users would not get trashed, but you would end up with two sets of users with index < 10, with and wihtout a leading zero.

**Comment by ocaisa** [comment]
Ok, I can live with this, I just need to remember to avoid having less than 10 users (or add my users another way)

**Comment by cmd-ntrf** [comment]
The same would happen when increasing by an order of magnitude (i.e: 100 -> 1000).

**Pull request merged**
