### PR TITLE
Generalize ceph.pp to allow multiple cephfs mounting

### PR DESCRIPTION
**Pull request by cmd-ntrf**

### CODE REVIEW

**Comment by mboisson** [comment]
Looks good to me. Works as intended to mount 4 different CephFS shares.

**Comment by mboisson** [comment]
I opened PR #314 to allow mount binds to be of files in addition to directories

**Review by mboisson — APPROVED** [review]
Looks good to me

**Comment by poquirion** [comment]
I have cherry picked the changes here and used cephFS for /home and got this when login in:

```
Could not chdir to home directory /home/poq: No such file or directory
 ```

I guess the cephfs should be mounted before the user are created. I am not shure how that would be done contitionally. I guess there is some way of handly that when using nfs. That also means that the cephFS needs to be mounted on the system where FreeIPA is running

**Comment by mboisson** [comment]
> I have cherry picked the changes here and used cephFS for /home and got this when login in:
> 
> ```
> Could not chdir to home directory /home/poq: No such file or directory
> ```
> 
> I guess the cephfs should be mounted before the user are created. I am not shure how that would be done contitionally. I guess there is some way of handly that when using nfs. That also means that the cephFS needs to be mounted on the system where FreeIPA is running

You may want this one for this use case: 
https://github.com/ComputeCanada/puppet-magic_castle/pull/317

**Comment by poquirion** [comment]
One cherry at a time, untill all is upstream. Thanks @mboisson 
```[poq@login1 ~]$ pwd
/home/poq
```

**Pull request merged**
